# Generated by Django 5.1.1 on 2024-09-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvivero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivero',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
